name: Build and Push Node Fastify Container

on:
    push:
        branches: 
            - main
    workflow_dispatch:

jobs:
  build-and-push-node-fastify-backend-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./node-fastify-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-fastify-backend:latest