name: Build and Test Containers

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  build-and-test-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Changed Directories
        id: get-changed-dirs
        run: |
          # Get the list of changed directories
          # Get the list of changed files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Get unique directories containing the changed files
          changed_dirs=$(echo "$changed_files" | xargs -n 1 dirname | sort | uniq)

          # Print the directories
          echo "Changed directories:"
          echo "$changed_dirs"