name: Build and Test Containers

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  build-and-test-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Changed Directories
        id: get-changed-dirs
        run: |
          # Input
          GITHUB_PULL_REQUEST_NUMBER='${{ github.event.number == '' && github.event.pull_request.number || github.event.number }}'

          # Get the list of changed files in the pull request
          CHANGED_FILES=$(gh api "/repos/$GITHUB_REPOSITORY/pulls/$GITHUB_PULL_REQUEST_NUMBER/files" --jq '.[].filename' --paginate)

          # Print the list of changed files
          echo "Changed Files"
          echo "============="
          echo "$CHANGED_FILES"
          echo ""

          # Get unique directories based on known changed files
          RAW_UNIQUE_CHANGED_DIRECTORIES=$(echo $CHANGED_FILES | sed 's/ /\n/g' | sed 's:[^/]*$::' | sort | uniq)
          
          echo "Raw Unique Changed Directories"
          echo "=============================="
          for dir in $RAW_UNIQUE_CHANGED_DIRECTORIES; do
              echo "$dir"
          done
          echo ""

          # Check for Dockerfiles in the directories
          CHANGED_DOCKERFILE_DIRECTORY=""
          for RAW_DIR in $RAW_UNIQUE_CHANGED_DIRECTORIES; do
              echo "Working on: $RAW_DIR"

              # Check if Dockerfile exists in the directory
              if [ -d "$RAW_DIR" ] && [ -n "$(find "$RAW_DIR" -maxdepth 1 -type f -name 'Dockerfile')" ]; then
                  echo "Directory contains Dockerfiles"
                  CHANGED_DOCKERFILE_DIRECTORY="${CHANGED_DOCKERFILE_DIRECTORY} $RAW_DIR"
              fi
          done

          # Print the unique changed directories containing Dockerfiles
          echo "Unique Changed Directories"
          echo "==========================="
          echo "$CHANGED_DOCKERFILE_DIRECTORY"

          # Set the output variable
          echo "CHANGED_DOCKERFILE_DIRECTORY=$CHANGED_DOCKERFILE_DIRECTORY" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build and Test Containers
        if: steps.get-changed-dirs.outputs.CHANGED_DOCKERFILE_DIRECTORY != ''
        run: |
          echo "Building and Testing Containers"
          echo "==============================="
          echo "Changed Directories: $CHANGED_DOCKERFILE_DIRECTORY"
          echo ""

          # Build and test the containers
          for DIR in $CHANGED_DOCKERFILE_DIRECTORY; do
              echo "Working on: $DIR"
              cd $DIR
              docker build -t $DIR .
              docker run $DIR
              cd ..
          done

          echo "Finished Building and Testing Containers"
        env:
          GITHUB_TOKEN: ${{ github.token }}
    

    