name: Build and Deploy Go Gin Backend Container

on:
    push:
        branches: 
            - main
        paths: 
          - 'go-gin-backend/**'
    workflow_dispatch:

jobs:
  cd-build-and-deploy-go-gin-backend-container:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up tag version
        id: tag
        run: echo "tag-version=$(date +'%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and deploy go-gin-backend for x64
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:./go-gin-backend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-gin-backend:latest,${{ secrets.DOCKERHUB_USERNAME }}/go-gin-backend:${{ steps.tag.outputs.tag-version }}
      
      - name: Build and deploy go-gin-backend for ARM64 (aarch64)
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:./go-gin-backend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-gin-backend:latest-arm64,${{ secrets.DOCKERHUB_USERNAME }}/go-gin-backend:${{ steps.tag.outputs.tag-version }}-arm64
          platforms: linux/arm64
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cloudflared
        run: |
          # Add cloudflare gpg key
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          
          # Add this repo to your apt repositories
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          
          # install cloudflared
          sudo apt-get update && sudo apt-get install cloudflared

      - name: Update go-gin-backend manifest
        run: |
          sed -i "s/image: encores\/go-gin-backend:.*/image: encores\/go-gin-backend:${{ steps.tag.outputs.tag-version }}/g" go-gin-backend-manifest.yaml
     
      - name: Deploy go-gin-backend
        run: |
          # Create a directory for the deployment
          sshpass -p ${{ secrets.SSH_PASSWORD }} \
          ssh -o ProxyCommand="cloudflared access ssh --hostname ${{ secrets.SSH_HOST }}" \
          -o StrictHostKeychecking=no \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          'mkdir -p ~/kubernetes/deployments'

          # Copy the deployment manifest to the deployment directory
          sshpass -p ${{ secrets.SSH_PASSWORD }} \
          scp -o ProxyCommand="cloudflared access ssh --hostname ${{ secrets.SSH_HOST }}" \
          -o StrictHostKeyChecking=no \
          go-gin-backend-manifest.yaml \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/kubernetes/deployments/go-gin-backend-manifest.yaml

          # Apply the deployment manifest
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh \
          -o ProxyCommand="cloudflared access \
          ssh --hostname ${{ secrets.SSH_HOST }}" \
          -o StrictHostKeychecking=no \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          'sudo kubectl apply -f ~/kubernetes/deployments/go-gin-backend-manifest.yaml'